name: core
channels:
  - defaults
  - pytorch
dependencies:
  - pip
  - python
  # - pytorch
  # - torchvision
  # - cudatoolkit
  - tensorflow
  - tensorboard
  - absl-py
  - pyparsing
  - pillow
  - h5py
  - pyyaml
  - moviepy
  - numpy
  - conda-forge::matplotlib
  - conda-forge::gym
  - conda-forge::ffmpeg
  - conda-forge::libiconv
  - conda-forge::imageio
  - pip:
    - termcolor
    # - dm_control
